print('-'*35)
print("Tugas 1 SISOP Kelas-A")
print('-'*35)
print("Nama: Novita Anggraini")
print("NPM: 21083010104")
print("-"*35)
print("Notes:")
print("-"*35)
print("Halo dunia!")
print("Ini adalah skrip Bash pertamaku di Linux!")
